Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,10 +41,21 @@ jobs:
     - name : mvn install
       run : mvn install -DskipTests
 
+    # - name: Snyk security scan
+    #   run: npx snyk test --severity-threshold=high
+    #   env:
+    #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
     - name: Snyk security scan
-      run: npx snyk test --severity-threshold=high
+      run: |
+        severity=$(npx snyk test --severity-threshold=high --json | jq -r '.vulnerabilities[].severity' | sort | tail -n 1)
+        if [ "$severity" == "critical" ] || [ "$severity" == "high" ]; then
+          echo "Found vulnerabilities with severity: $severity. Failing the job."
+        exit 1
+        fi
       env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
   
     # Generate code-coverage report using jacoco
     - name : Get code-coverage report
