Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -40,55 +40,37 @@ jobs:
     - name : mvn install
       run : mvn install -DskipTests
 
-    # - name: Snyk security scan
-    #   run: npx snyk test --severity-threshold=high
-    #   env:
-    #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-    - name: Snyk security scan
-      run: |
-        severity=$(npx snyk test --severity-threshold=high --json | jq -r '.vulnerabilities[].severity' | sort | tail -n 1)
-        if [ "$severity" == "critical" ] || [ "$severity" == "high" ]; then
-          echo "Found vulnerabilities with severity: $severity. Failing the job."
-        exit 1
-        fi
+    # - name: Snyk security scan
+    #   run: |
+    #     severity=$(npx snyk test --severity-threshold=high --json | jq -r '.vulnerabilities[].severity' | sort | tail -n 1)
+    #     if [ "$severity" == "critical" ] || [ "$severity" == "high" ]; then
+    #       echo "Found vulnerabilities with severity: $severity. Failing the job."
+    #     exit 1
+    #     fi
+    #   env:
+    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+
+    - name: Run Snyk to check for high severity vulnerabilities
+      id: snyk_high
+      uses: snyk/actions/maven@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      with:
+        args: "--severity-threshold=high"
 
-    - name: Snyk security scan
-      run: |
-       snyk_output=$(npx snyk test --severity-threshold=high --json)
-       echo "Snyk output:"
-       echo "$snyk_output"
-       severity=$(echo "$snyk_output" | jq -r '.vulnerabilities[].severity' | sort | tail -n 1)
-       echo "Severity found: $severity"
-       if [ "$severity" == "critical" ] || [ "$severity" == "high" ]; then
-         echo "Found vulnerabilities with severity: $severity. Failing the job."
-       exit 1
-       fi
-       env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+    - name: Run Snyk to check for critical severity vulnerabilities
+      id: snyk_critical
+      uses: snyk/actions/maven@master
+      env:
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      with:
+        args: "--severity-threshold=critical"
 
-
-    # - name: Run Snyk to check for high severity vulnerabilities
-    #   id: snyk_high
-    #   uses: snyk/actions/maven@master
-    #   env:
-    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-    #   with:
-    #     args: "--severity-threshold=high"
-
-    # - name: Run Snyk to check for critical severity vulnerabilities
-    #   id: snyk_critical
-    #   uses: snyk/actions/maven@master
-    #   env:
-    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-    #   with:
-    #     args: "--severity-threshold=critical"
-
-    # - name: Fail if high or critical vulnerabilities found
-    #   if: ${{ steps.snyk_high.outputs.summary.vulnerabilities.high > 0 || steps.snyk_critical.outputs.summary.vulnerabilities.critical > 0 }}
-    #   run: exit 1
+    - name: Fail if high or critical vulnerabilities found
+      if: ${{ steps.snyk_high.outputs.summary.vulnerabilities.high > 0 || steps.snyk_critical.outputs.summary.vulnerabilities.critical > 0 }}
+      run: exit 1
   
     # # Generate code-coverage report using jacoco
     # - name : Get code-coverage report
